In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
data = pd.read_csv('Telco_Customer_Churn.csv')

In [3]:
data.head(10)

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   
5  Female              0      No         No       8          Yes   
6    Male              0      No        Yes      22          Yes   
7  Female              0      No         No      10           No   
8  Female              0     Yes         No      28          Yes   
9    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   
5               Yes     Fiber optic             No           No   
6               Yes     Fiber optic             No          Yes   
7  No phone service             DSL            Yes           No   
8               Yes     Fiber optic             No           No   
9                No             DSL            Yes          Yes   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   
5              Yes          No         Yes             Yes  Month-to-month   
6               No          No         Yes              No  Month-to-month   
7               No          No          No              No  Month-to-month   
8              Yes         Yes         Yes             Yes  Month-to-month   
9               No          No          No              No        One year   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   
5              Yes           Electronic check           99.65        820.50   
6              Yes    Credit card (automatic)           89.10       1949.40   
7               No               Mailed check           29.75        301.90   
8              Yes           Electronic check          104.80       3046.05   
9               No  Bank transfer (automatic)           56.15       3487.95   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes  
5   Yes  
6    No  
7    No  
8   Yes  
9    No

In [4]:
data.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
data.shape

(7032, 20)

In [6]:
data.describe()

SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   7032.000000
mean        0.162400    32.421786       64.798208   2283.300441
std         0.368844    24.545260       30.085974   2266.771362
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.587500    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.862500   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [7]:
data.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [8]:
gender = pd.get_dummies(data['gender'],drop_first=True)
Partner = pd.get_dummies(data['Partner'],drop_first=True)
Dependents = pd.get_dummies(data['Dependents'],drop_first=True)
PhoneService = pd.get_dummies(data['PhoneService'],drop_first=True)
MultipleLines = pd.get_dummies(data['MultipleLines'],drop_first=True)
InternetService = pd.get_dummies(data['InternetService'],drop_first=True)
OnlineSecurity = pd.get_dummies(data['OnlineSecurity'],drop_first=True)
OnlineBackup = pd.get_dummies(data['OnlineBackup'],drop_first=True)
DeviceProtection = pd.get_dummies(data['DeviceProtection'],drop_first=True)
TechSupport = pd.get_dummies(data['TechSupport'],drop_first=True)
StreamingTV = pd.get_dummies(data['StreamingTV'],drop_first=True)
StreamingMovies = pd.get_dummies(data['StreamingMovies'],drop_first=True)
Contract = pd.get_dummies(data['Contract'],drop_first=True)
PaperlessBilling = pd.get_dummies(data['PaperlessBilling'],drop_first=True)
PaymentMethod = pd.get_dummies(data['PaymentMethod'],drop_first=True)
Churn = pd.get_dummies(data['Churn'],drop_first=True)


data.drop(['gender','Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
          'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn'],axis=1,inplace=True)
data = pd.concat([data,gender, Partner, Dependents, PhoneService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, 
                 StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, Churn],axis=1)


data

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Male  Yes  Yes  \
0                 0       1           29.85         29.85     0    1    0   
1                 0      34           56.95       1889.50     1    0    0   
2                 0       2           53.85        108.15     1    0    0   
3                 0      45           42.30       1840.75     1    0    0   
4                 0       2           70.70        151.65     0    0    0   
...             ...     ...             ...           ...   ...  ...  ...   
7027              0      24           84.80       1990.50     1    1    1   
7028              0      72          103.20       7362.90     0    1    1   
7029              0      11           29.60        346.45     0    1    1   
7030              1       4           74.40        306.60     1    1    0   
7031              0      66          105.65       6844.50     1    0    0   

      Yes  No internet service  Yes  ...  Yes  No internet service  Yes  \
0       0                    0    0  ...    0                    0    0   
1       1                    0    1  ...    0                    0    0   
2       1                    0    1  ...    0                    0    0   
3       0                    0    1  ...    0                    0    0   
4       1                    0    0  ...    0                    0    0   
...   ...                  ...  ...  ...  ...                  ...  ...   
7027    1                    0    1  ...    1                    0    1   
7028    1                    0    0  ...    1                    0    1   
7029    0                    0    1  ...    0                    0    0   
7030    1                    0    0  ...    0                    0    0   
7031    1                    0    1  ...    1                    0    1   

      One year  Two year  Yes  Credit card (automatic)  Electronic check  \
0            0         0    1                        0                 1   
1            1         0    0                        0                 0   
2            0         0    1                        0                 0   
3            1         0    0                        0                 0   
4            0         0    1                        0                 1   
...        ...       ...  ...                      ...               ...   
7027         1         0    1                        0                 0   
7028         1         0    1                        1                 0   
7029         0         0    1                        0                 1   
7030         0         0    1                        0                 0   
7031         0         1    1                        0                 0   

      Mailed check  Yes  
0                0    0  
1                1    0  
2                1    1  
3                0    0  
4                0    1  
...            ...  ...  
7027             1    0  
7028             0    0  
7029             0    0  
7030             1    1  
7031             0    0  

[7032 rows x 27 columns]

In [9]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101 )

## Logistic Regression

In [81]:
lm = LogisticRegression()

In [82]:
lm = lm.fit(X_train, y_train)

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [83]:
y_pred = lm.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [84]:
y_test

4246    0
2909    0
1564    0
5218    0
4419    0
       ..
2919    1
2294    0
1230    0
834     0
1641    0
Name: Yes, Length: 2321, dtype: uint8

In [85]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pred))

Classification report:
               precision    recall  f1-score   support

           0       0.86      0.89      0.87      1734
           1       0.64      0.57      0.60       587

    accuracy                           0.81      2321
   macro avg       0.75      0.73      0.74      2321
weighted avg       0.80      0.81      0.81      2321



In [86]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.72943573661552

## SVM

In [16]:
from sklearn import svm

In [17]:
cl = svm.SVC(kernel = 'linear')

In [18]:
cl.fit(X_train, y_train)

SVC(kernel='linear')

In [22]:
y_pr = cl.predict(X_test)
y_pr

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [23]:
print('Accuracy', metrics.accuracy_score(y_test, y_pr))
print('Precision', metrics.precision_score(y_test, y_pr))
print('Recall', metrics.recall_score(y_test, y_pr))

Accuracy 0.8031021111589832
Precision 0.6692708333333334
Recall 0.43781942078364566


In [24]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr))

Classification report:
               precision    recall  f1-score   support

           0       0.83      0.93      0.88      1734
           1       0.67      0.44      0.53       587

    accuracy                           0.80      2321
   macro avg       0.75      0.68      0.70      2321
weighted avg       0.79      0.80      0.79      2321



In [25]:
cl2 = svm.SVC(kernel = 'rbf')

In [26]:
cl2.fit(X_train, y_train)

SVC()

In [27]:
y_pr2 = cl2.predict(X_test)
y_pr2

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [29]:
print('Accuracy', metrics.accuracy_score(y_test, y_pr2))
print('Precision', metrics.precision_score(y_test, y_pr2))
print('Recall', metrics.recall_score(y_test, y_pr2))

Accuracy 0.7470917707884532
Precision 0.0
Recall 0.0


C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr2))

Classification report:
               precision    recall  f1-score   support

           0       0.75      1.00      0.86      1734
           1       0.00      0.00      0.00       587

    accuracy                           0.75      2321
   macro avg       0.37      0.50      0.43      2321
weighted avg       0.56      0.75      0.64      2321



C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Decision tree

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
cl = DecisionTreeClassifier()

In [33]:
cl.fit(X_train, y_train)

DecisionTreeClassifier()

In [35]:
y_pr = cl.predict(X_test)
y_pr

array([0, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [36]:
print('Accuracy', metrics.accuracy_score(y_test, y_pr))
print('Precision', metrics.precision_score(y_test, y_pr))
print('Recall', metrics.recall_score(y_test, y_pr))

Accuracy 0.7406290392072382
Precision 0.48833592534992226
Recall 0.534923339011925


In [37]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr))

Classification report:
               precision    recall  f1-score   support

           0       0.84      0.81      0.82      1734
           1       0.49      0.53      0.51       587

    accuracy                           0.74      2321
   macro avg       0.66      0.67      0.67      2321
weighted avg       0.75      0.74      0.74      2321



In [50]:
cl2 = DecisionTreeClassifier(criterion='entropy')

In [51]:
cl2 = cl2.fit(X_train, y_train)

In [52]:
y_pr2 = cl2.predict(X_test)

In [53]:
print('Accuracy:', metrics.accuracy_score(y_test, y_pr2))
print('Precision:', metrics.precision_score(y_test, y_pr2))
print('Recall:', metrics.recall_score(y_test, y_pr2))

Accuracy: 0.7432141318397243
Precision: 0.49293563579277866
Recall: 0.534923339011925


In [54]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr2))

Classification report:
               precision    recall  f1-score   support

           0       0.84      0.81      0.83      1734
           1       0.49      0.53      0.51       587

    accuracy                           0.74      2321
   macro avg       0.67      0.67      0.67      2321
weighted avg       0.75      0.74      0.75      2321



## Random forest

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
cl = RandomForestClassifier()

In [60]:
cl = cl.fit(X_train, y_train)

In [61]:
y_pr = cl.predict(X_test)

In [62]:
print('Accuracy', metrics.accuracy_score(y_test, y_pr))
print('Precision', metrics.precision_score(y_test, y_pr))
print('Recall', metrics.recall_score(y_test, y_pr))

Accuracy 0.7845756139595003
Precision 0.5908141962421712
Recall 0.48211243611584326


In [63]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr))

Classification report:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86      1734
           1       0.59      0.48      0.53       587

    accuracy                           0.78      2321
   macro avg       0.71      0.68      0.70      2321
weighted avg       0.77      0.78      0.78      2321



## NaiveBayes

In [64]:
from sklearn.naive_bayes import GaussianNB

In [65]:
gn = GaussianNB()

In [66]:
gn = gn.fit(X_train, y_train)

In [67]:
y_pr = gn.predict(X_test)

In [70]:
print('Accuracy:', metrics.accuracy_score(y_test, y_pr))
print('Precision:', metrics.precision_score(y_test, y_pr))
print('Recall:', metrics.recall_score(y_test, y_pr))

Accuracy: 0.6596294700560104
Precision: 0.4146341463414634
Recall: 0.8398637137989778


In [71]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr))

Classification report:
               precision    recall  f1-score   support

           0       0.92      0.60      0.72      1734
           1       0.41      0.84      0.56       587

    accuracy                           0.66      2321
   macro avg       0.67      0.72      0.64      2321
weighted avg       0.79      0.66      0.68      2321



## KNN

In [72]:
from sklearn.neighbors import KNeighborsClassifier

In [73]:
kn = KNeighborsClassifier()

In [74]:
kn = kn.fit(X_train, y_train)

In [75]:
y_pr = kn.predict(X_test)

In [76]:
print('Accuracy:', metrics.accuracy_score(y_test, y_pr))
print('Precision:', metrics.precision_score(y_test, y_pr))
print('Recall:', metrics.recall_score(y_test, y_pr))

Accuracy: 0.7725118483412322
Precision: 0.5605749486652978
Recall: 0.46507666098807493


In [77]:
print('Classification report:''\n', metrics.classification_report(y_test, y_pr))

Classification report:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85      1734
           1       0.56      0.47      0.51       587

    accuracy                           0.77      2321
   macro avg       0.69      0.67      0.68      2321
weighted avg       0.76      0.77      0.77      2321

